// Package store persists a run to disk.
//
// It is a concrete type, not an interface. There is exactly one implementation,
// and an interface with one implementation is indirection rather than
// abstraction. Go's implicit interfaces make extracting one a non-event when a
// second implementation actually exists, and callers can declare a narrow
// interface at the point of use.
//
// The seam that matters is kept: nothing outside this package constructs a
// filesystem path for run data.
package store

import (
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
	"sync"
	"time"

	"crypto/sha256"

	"github.com/jaylordibe/application-security-framework/internal/model"
)

// File modes. Evidence contains redacted-but-still-sensitive material, so the
// run directory is owner-only.
const (
	dirMode  os.FileMode = 0o700
	fileMode os.FileMode = 0o600
)

// FormatVersion identifies the on-disk layout. A newer major version is refused
// rather than misread.
const FormatVersion = "assay.run/v1alpha1"

// Run is one assessment's directory.
type Run struct {
	id   string
	dir  string
	mu   sync.Mutex
	seen map[string]struct{}
}

// Meta is the run directory's manifest.
type Meta struct {
	FormatVersion string    `json:"formatVersion"`
	RunID         string    `json:"runId"`
	CreatedAt     time.Time `json:"createdAt"`
	// Note explains the directory's sensitivity to whoever finds it later.
	Note string `json:"note"`
}

// Create makes a run directory under root.
//
// The run id is generated by the caller and must be filesystem-safe; it is
// validated here rather than trusted, because a target-influenced name must
// never become a path.
func Create(root, runID string, now time.Time) (*Run, error) {
	if err := validateRunID(runID); err != nil {
		return nil, err
	}
	dir := filepath.Join(root, "runs", runID)
	if err := os.MkdirAll(dir, dirMode); err != nil {
		return nil, fmt.Errorf("store: cannot create run directory: %w", err)
	}
	// MkdirAll respects umask, so set the mode explicitly.
	if err := os.Chmod(dir, dirMode); err != nil {
		return nil, fmt.Errorf("store: cannot set run directory permissions: %w", err)
	}
	if err := os.MkdirAll(filepath.Join(dir, "evidence"), dirMode); err != nil {
		return nil, fmt.Errorf("store: cannot create evidence directory: %w", err)
	}

	r := &Run{id: runID, dir: dir, seen: map[string]struct{}{}}
	meta := Meta{
		FormatVersion: FormatVersion,
		RunID:         runID,
		CreatedAt:     now,
		Note: "This directory contains captured HTTP evidence. Secrets are redacted at capture " +
			"time, but redaction is a mitigation and not a guarantee. Do not commit this " +
			"directory to version control.",
	}
	if err := r.WriteJSON("meta.json", meta); err != nil {
		return nil, err
	}
	return r, nil
}

// Dir returns the run directory.
func (r *Run) Dir() string { return r.dir }

// Path returns the absolute path of a file in the run directory, so callers can
// display it without constructing run paths themselves.
func (r *Run) Path(name string) string { return filepath.Join(r.dir, name) }

// ID returns the run id.
func (r *Run) ID() string { return r.id }

// WriteJSON writes a JSON document into the run directory atomically.
func (r *Run) WriteJSON(name string, v any) error {
	data, err := json.MarshalIndent(v, "", "  ")
	if err != nil {
		return fmt.Errorf("store: cannot encode %s: %w", name, err)
	}
	data = append(data, '\n')
	return r.WriteFile(name, data)
}

// WriteFile writes a file into the run directory atomically.
//
// The write goes to a temporary file which is chmod'd before being renamed into
// place, so the final path never exists with permissive modes, and a reader
// never sees a partially written file.
func (r *Run) WriteFile(name string, data []byte) error {
	dest, err := r.lexicalResolve(name)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(dest), dirMode); err != nil {
		return fmt.Errorf("store: %w", err)
	}
	// Only now can the parent be resolved. Checking before MkdirAll would skip
	// the symlink gate entirely for any not-yet-created directory.
	if err := r.assertContained(dest); err != nil {
		return err
	}

	tmp, err := os.CreateTemp(filepath.Dir(dest), ".tmp-*")
	if err != nil {
		return fmt.Errorf("store: %w", err)
	}
	tmpName := tmp.Name()
	defer func() { _ = os.Remove(tmpName) }()

	if err := tmp.Chmod(fileMode); err != nil {
		_ = tmp.Close()
		return fmt.Errorf("store: cannot set file permissions: %w", err)
	}
	if _, err := tmp.Write(data); err != nil {
		_ = tmp.Close()
		return fmt.Errorf("store: %w", err)
	}
	if err := tmp.Sync(); err != nil {
		_ = tmp.Close()
		return fmt.Errorf("store: %w", err)
	}
	if err := tmp.Close(); err != nil {
		return fmt.Errorf("store: %w", err)
	}
	if err := os.Rename(tmpName, dest); err != nil {
		return fmt.Errorf("store: %w", err)
	}
	return nil
}

// PutEvidence stores an exchange and returns its reference.
//
// Evidence is content-addressed over the redacted bytes, so identical exchanges
// are stored once and a finding can reference rather than embed them. Writes are
// idempotent, which makes concurrent stores of the same digest safe.
func (r *Run) PutEvidence(ex model.Exchange) (string, error) {
	payload, err := json.MarshalIndent(exchangeDoc{
		SchemaVersion: "assay.evidence/v1alpha1",
		Request: requestDoc{
			Method:        ex.Request.Method,
			URL:           ex.Request.URL,
			Header:        sortedHeader(ex.Request.Header),
			Body:          string(ex.Request.Body),
			BodyTruncated: ex.Request.BodyTruncated,
		},
		Response: responseDoc(ex.Response),
		Error:    ex.Err,
	}, "", "  ")
	if err != nil {
		return "", fmt.Errorf("store: cannot encode evidence: %w", err)
	}
	sum := sha256.Sum256(payload)
	ref := "sha256:" + hex.EncodeToString(sum[:])
	name := filepath.Join("evidence", hex.EncodeToString(sum[:])+".json")

	r.mu.Lock()
	_, already := r.seen[ref]
	if !already {
		r.seen[ref] = struct{}{}
	}
	r.mu.Unlock()
	if already {
		return ref, nil
	}
	if err := r.WriteFile(name, append(payload, '\n')); err != nil {
		return "", err
	}
	return ref, nil
}

// WriteFingerprintKey stores the per-run redaction key.
//
// It lives beside the evidence and never inside a report, so fingerprints stay
// correlatable within a run without a shared report enabling offline guessing or
// cross-run correlation.
func (r *Run) WriteFingerprintKey(key []byte) error {
	return r.WriteFile("fingerprint.key", []byte(hex.EncodeToString(key)+"\n"))
}

// lexicalResolve validates a relative name and returns an absolute path,
// rejecting traversal and absolute paths. It does not touch the filesystem.
func (r *Run) lexicalResolve(name string) (string, error) {
	if name == "" {
		return "", errors.New("store: empty file name")
	}
	if filepath.IsAbs(name) {
		return "", fmt.Errorf("store: %q must be relative to the run directory", name)
	}
	clean := filepath.Clean(name)
	if clean == "." || strings.HasPrefix(clean, "..") {
		return "", fmt.Errorf("store: %q escapes the run directory", name)
	}
	dest := filepath.Join(r.dir, clean)

	rel, err := filepath.Rel(r.dir, dest)
	if err != nil || strings.HasPrefix(rel, "..") {
		return "", fmt.Errorf("store: %q escapes the run directory", name)
	}
	return dest, nil
}

// assertContained verifies that the destination's real parent is still inside
// the run directory, so a symlinked parent cannot redirect a write. A resolution
// error is a refusal, not a pass.
func (r *Run) assertContained(dest string) error {
	base, err := filepath.EvalSymlinks(r.dir)
	if err != nil {
		return fmt.Errorf("store: cannot resolve the run directory: %w", err)
	}
	parent, err := filepath.EvalSymlinks(filepath.Dir(dest))
	if err != nil {
		return fmt.Errorf("store: cannot resolve the destination directory: %w", err)
	}
	rel, err := filepath.Rel(base, parent)
	if err != nil || strings.HasPrefix(rel, "..") {
		return fmt.Errorf("store: %q resolves outside the run directory", dest)
	}
	return nil
}

// validateRunID refuses anything that is not a plain identifier, so a name can
// never traverse or collide with a reserved device name.
func validateRunID(id string) error {
	if id == "" {
		return errors.New("store: run id is empty")
	}
	if len(id) > 64 {
		return errors.New("store: run id is too long")
	}
	for _, r := range id {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9', r == '-', r == '_':
		default:
			return fmt.Errorf("store: run id contains an unsupported character %q", r)
		}
	}
	return nil
}

// PermissionsEnforced reports whether the platform actually honours the
// owner-only file modes this package sets.
//
// On Windows, os.Chmod only toggles the read-only attribute, so 0600 is not
// enforced. Saying so lets the CLI warn instead of implying a protection that
// does not exist.
func PermissionsEnforced() bool { return runtime.GOOS != "windows" }

type exchangeDoc struct {
	SchemaVersion string       `json:"schemaVersion"`
	Request       requestDoc   `json:"request"`
	Response      *responseDto `json:"response,omitempty"`
	Error         string       `json:"error,omitempty"`
}

type requestDoc struct {
	Method        string              `json:"method"`
	URL           string              `json:"url"`
	Header        map[string][]string `json:"header,omitempty"`
	Body          string              `json:"body,omitempty"`
	BodyTruncated bool                `json:"bodyTruncated,omitempty"`
}

type responseDto struct {
	Status        int                 `json:"status"`
	Proto         string              `json:"proto,omitempty"`
	Header        map[string][]string `json:"header,omitempty"`
	Body          string              `json:"body,omitempty"`
	BodyTruncated bool                `json:"bodyTruncated,omitempty"`
	ElapsedMS     int64               `json:"elapsedMs"`
}

func responseDoc(r *model.CapturedResponse) *responseDto {
	if r == nil {
		return nil
	}
	return &responseDto{
		Status:        r.Status,
		Proto:         r.Proto,
		Header:        sortedHeader(r.Header),
		Body:          string(r.Body),
		BodyTruncated: r.BodyTruncated,
		ElapsedMS:     r.Elapsed.Milliseconds(),
	}
}

// sortedHeader returns a copy with deterministic value ordering, so identical
// exchanges hash identically.
func sortedHeader(h map[string][]string) map[string][]string {
	if len(h) == 0 {
		return nil
	}
	out := make(map[string][]string, len(h))
	for k, v := range h {
		cp := append([]string(nil), v...)
		sort.Strings(cp)
		out[k] = cp
	}
	return out
}
